spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
#    password: quntum88
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 10000ms

  profiles:
    active: @profiles.active@
  cloud:
    loadbalancer:
      retry:
        enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

logging:
  level:
    com.renyijia: debug

info:
  app:
    name: user-servive
    version: v1.0.0