spring:
  profiles:
    active: test

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/


logging:
  level:
    com.renyijia: debug

info:
  app:
    name: user-servive
    version: v1.0.0